### ISSUE TITLE
[feature] Syntax highlighting of Maven output

### ISSUE THREAD

**Issue by lervag** [oclay1st/maven.nvim#1]
Ok, first: I think this is _very_ useful. Thanks!

Now, it would be awesome if we could add some basic highlighting of the maven output. As a few first pointers:

* The top line command could be highlighted
* The severity indicators, e.g. `[INFO]`, could be highlighted
* Key output like `BUILD SUCCESS` could be highlighted

Probably more, but that's a nice start I think.

**Comment by oclay1st** [comment]
So far I have found two possible solutions for this. 

The first solution is to use the `nvim_open_term` api that allows to display ANSI terminal outputs but unfortunately it doesn't play nicely with others behaviors of the console buffer. 

The second solution (the current one) is to implement your suggestions in addition to the current behaviors.
I also added a property to clean up or preserve the output of previous commands.

A recent OS update broke my git client but I'll be submitting the code for this improvement asap.

![Screenshot_20241113_213815](https://github.com/user-attachments/assets/002fdb56-f99b-48c4-be33-d750de9b6175)

**Comment by lervag** [comment]
> So far I have found two possible solutions for this.
> 
> The first solution is to use the `nvim_open_term` api that allows to display ANSI terminal outputs but unfortunately it doesn't play nicely with others behaviors of the console buffer.

IMHO, this is not a very good solution, because it is not as flexible as relying on some syntax rules.

> The second solution (the current one) is to implement your suggestions in addition to the current behaviors. I also added a property to clean up or preserve the output of previous commands.

Yes, I think properly cleaning out the ANSI codes and then using syntax rules and standard Vim highlighting is a better way to do it. I have a lot of experience with this, so let me know if you want help with it.

> A recent OS update broke my git client but I'll be submitting the code for this improvement asap.

Great; and no rush - these are all cosmetic improvements. The plugin seems to work very well in general.

The screenshot looks great!

**Comment by lervag** [comment]
It seems you already fixed this as well. Great job! Since you didn't close the issue, perhaps you have further plans?

From my point of view, this is already good enough to be useful!
