### ISSUE TITLE
[feature] Allow to configure the floating window options (e.g. border)

### ISSUE THREAD

**Issue by lervag** [oclay1st/maven.nvim#2]
I use a custom border for most of my floating windows and I would prefer if I could also use this with maven.nvim.

Now, I see you use `nui.nvim`, so I guess what I would want is a possibility for adjusting the options passed to `Popup`. That would also make it very easy to apply other useful user customizations.

Basically, I would want a config table that would be merged with the `*_win_opts` e.g. here:

https://github.com/oclay1st/maven.nvim/blob/900d2198455aff0ce9059807ee320f949d7b762a/lua/maven/ui/dependencies_view.lua#L97-L101

**Comment by oclay1st** [comment]
Let me know if the the recent changes work for you!

**Comment by lervag** [comment]
Yes, that's very good, thanks! 🎊
